<ADSWorkspace Revision="4" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="dds.cfg" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Data_Display Name="LNA Common source.dds" />
        <Log Name="netlist.log" />
        <Log Name="search_history.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="Projek Mikroelektronika_lib_lay.prf" />
        <Preferences Name="schematic.prf" />
        <Dataset Name="LNA_Common_source.ds" />
        <Data_Files Name="LNA_Common_source.ds" />
        <Data_Files Name="LNA_Common_source_data\logFile.txt" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="Projek Mikroelektronika_lib" />
        <Library Name="RenesasElectronics_ActiveDeviceLibrary_ver6_0_tech" />
        <Library Name="RenesasElectronics_ActiveDeviceLibrary_ver6_0" />
        <Library Name="RF_Transistors" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="Analog_Parts" />
        <Data_Display Name="kelompok13_LNA.dds" />
        <Dataset Name="__simdata079429.ds" />
        <Dataset Name="kelompok13_LNA.ds" />
        <Data_Files Name="kelompok13_LNA.ds" />
        <Data_Files Name="kelompok13_LNA_data\logFile.txt" />
        <Data_Files Name="__simdata079429.ds" />
        <Library Name="HFDiode" />
        <Library Name="RF_Passive_SMT" />
        <Library Name="Microwave_Transistors" />
        <Data_Files Name="dc_annotation\%Projek#20%Mikroelektronika_lib_kelompok13_%L%N%A_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%Projek#20%Mikroelektronika_lib_kelompok13_%L%N%A_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%Projek#20%Mikroelektronika_lib_%L%N%A#20%Common#20source_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%Projek#20%Mikroelektronika_lib_%L%N%A#20%Common#20source_schematic\annotation_map.xml" />
        <Cell Name="Projek Mikroelektronika_lib:kelompok13_LNA Common source" />
    </Workspace>
</ADSWorkspace>
